Fe uploader tests
CC451-Computer-Networks-TA-team/GraderX-FE pull request #20
Opened 2020-07-22 16:48 UTC by Hagar-Usama

2020-07-30 08:45 UTC, shakram02 commented
please resolve conflicts

2020-07-30 08:45 UTC, shakram02 requested changes
please resolve conflicts

2020-08-02 04:43 UTC, shakram02 submitted a review, later dismissed

2020-08-02 04:43 UTC, shakram02 commented on src/__tests__/FileUpload.test.js
> +describe('Testing File input', () => {
can you please run a formatter over all the project files? ensuring that it removes any extra white space (2+ empty lines) and also that every file ends with a new line

2020-09-02 23:37 UTC, amrable approved these changes, later dismissed

2020-09-03 00:06 UTC, amroakmal submitted a review, later dismissed

2020-09-03 00:37 UTC, amohamed97 submitted a review, later dismissed

2020-09-03 00:58 UTC, amohamed97 approved these changes

2020-09-03 00:58 UTC, amrable approved these changes

2020-09-03 00:59 UTC, amroakmal approved these changes

2020-09-03 00:59 UTC, merged