Google forms integration
CC451-Computer-Networks-TA-team/GraderX-FE pull request #22
Opened 2020-07-30 04:35 UTC by amohamed97

2020-07-30 08:47 UTC, shakram02 requested changes

2020-07-30 08:47 UTC, shakram02 commented on public/index.html
> +</html>
new line

2020-07-30 08:47 UTC, shakram02 commented on src/api-client.js
>      return axios.post(`http://localhost:5000/results/cc451/${labId}`, formData);
URLS should go in config variables/env variables

2020-07-30 08:47 UTC, shakram02 commented on src/components/grader/submissions/ImportSubmissions.js
> +export default ImportSubmissions
new line

2020-08-02 04:44 UTC, shakram02 requested changes

2020-08-02 04:44 UTC, shakram02 commented on src/api-client.js
> +    return axios.post(`${graderx_api}results/cc451/${labId}`, formData);
I think it should be `${GRADERX_API}/` note the trailing slash. just to make it very clear it's a base URL

2020-08-02 16:45 UTC, Hagar-Usama commented on package.json
> +    "react-google-login": "^5.1.21",
Do we implement it in FE?!

2020-08-02 19:01 UTC, Hagar-Usama submitted a review, later dismissed

2020-08-03 20:06 UTC, shakram02 approved these changes

2020-08-04 00:09 UTC, Hagar-Usama approved these changes

2020-08-05 19:51 UTC, merged