all core features
CC451-Computer-Networks-TA-team/GraderX-FE pull request #4
Opened 2020-07-16 14:31 UTC by amohamed97

2020-07-17 14:35 UTC, shakram02 reviewed
Great job :clap:

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/DownloadResult.js
> +        axios.get(`http://localhost:5000/results/cc451/${props.lab}`).then(res => {
please extract the website URL to a `config` file or something. Where it tries to fetch the variable from an environment variable first, then falls back to a default value

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/DownloadResult.js
> +export default DownloadResult
please make sure there's an empty line at the end of each file, a formatter extension will do that

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/FileUpload.js
> +                    Last Modified:{" "}
We don't really need the `lastModified` date

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/FileUpload.js
> +        axios.post(`http://localhost:5000/results/cc451/${props.lab}`, formData).then((res) =>{
please extract the main URL

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/LabSelector.js
> +        Axios.get(`http://localhost:5000/labs/cc451`).then((res) => {
extract (I'll repeat the comment so you can resolve it once you're done)

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/Grader.js
> +export default Grader
new line (I'll repeat the comment so you can resolve it once you're done)

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/LabSelector.js
> +export default LabSelector
new line

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/layout/Header.js
> +export default Header
new line

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/Grader.js
> +                <Paper elevation={5} style={{ 'padding': 25, 'minWidth':700}}>
will this work fine on a mobile screen? `minWidth:700`

2020-07-17 14:35 UTC, shakram02 commented on ui/src/components/grader/FileUpload.js
> +export default FileUpload;
new line

2020-07-19 09:21 UTC, shakram02 requested changes

2020-07-19 09:21 UTC, shakram02 commented on src/__tests__/__snapshots__/FileUpload.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
do we need this file?

2020-07-19 09:21 UTC, shakram02 commented on src/__tests__/FileUpload.js
> +});
add new line :3

2020-07-19 09:21 UTC, shakram02 commented on src/components/grader/FileUpload.js
> +    let supportedTypes = ["application/zip", "application/vnd.rar", "application/x-7z-compressed" ];
extract this to a const array, since it's never changing.

2020-07-20 04:55 UTC, Hagar-Usama commented on src/__tests__/__snapshots__/FileUpload.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Nope, removed + added to .gitignore

2020-07-21 08:32 UTC, shakram02 commented
why is `add upload spinner` in this branch?

2020-07-21 11:18 UTC, merged