Finish Courses
CC451-Computer-Networks-TA-team/GraderX-FE pull request #46
Opened 2020-10-10 17:54 UTC by NourEldinShobier

- Add
- Edit
- Delete

2020-10-10 22:05 UTC, Hagar-Usama requested changes

2020-10-10 22:05 UTC, Hagar-Usama commented on src/pages/Courses.js
> +        <TextInput
We may add `disabled = {isEdit}`

2020-10-10 22:05 UTC, Hagar-Usama commented on src/pages/Courses.js
> +  let [oldCourseName, setOldCourseName] = useState('');
**const**antize you **let**s :pray:

2020-10-17 20:44 UTC, amohamed97 approved these changes

2020-10-17 20:45 UTC, merged